### ISSUE TITLE
Switch To Hack Club CSS on the CDN

### ISSUE THREAD

**Issue by sampoder** [hackclub/contribute#11]
Currently these files are stored locally, as Hack Club CSS improves we want to be able to get these improvements here!

Relevant section of the CSS README:

> Get the latest theme stylesheet: [css.hackclub.com/theme.css](https://css.hackclub.com/theme.css)
> 
> Get the latest minified theme stylesheet: [css.hackclub.com/theme.min.css](https://css.hackclub.com/theme.min.css)
> 
> (HQ-only) Get the latest fonts stylesheet: [css.hackclub.com/fonts.css](https://css.hackclub.com/fonts.css)
> 
> (HQ-only) Get the latest minified fonts stylesheet: [css.hackclub.com/fonts.min.css](https://css.hackclub.com/fonts.min.css)[](https://github.com/hackclub/contribute/issues/new#archives)
> 

Thank you!

**Comment by jessicard** [comment]
@sampoder Good thinking!

**Comment by jessicard** [comment]
Fixed by @bellesea in https://github.com/hackclub/contribute/pull/13
