### ISSUE TITLE
Add fun background to repositories section

### ISSUE THREAD

**Issue by jessicard** [hackclub/contribute#17]
I love the background @bellesea added to the header section in https://github.com/hackclub/contribute/pull/13. Could we do something cool like that for the **active repositories** section? There's some cool background ideas in https://summer.hackclub.com/ 👀

**Comment by bellesea** [comment]
ooo, this would be super cool! i think it could be a good first issue too and if someone doesn't work on this, i'd love to take a crack at it this weekend :))

**Comment by abbyfischler** [comment]
#30
