### ISSUE TITLE
Deploy this site onto contribute.hackclub.com

### ISSUE THREAD

**Issue by jessicard** [hackclub/contribute#3]
Deploy this site onto contribute.hackclub.com.

Use https://github.com/hackclub/dns to add the subdomain.

Blocked until we finish the styling and content.

**Comment by bellesea** [comment]
Since this is up we can close the issue?

**Comment by jessicard** [comment]
@bellesea It's not deployed yet! :)

**Comment by bellesea** [comment]
oop, i saw https://contribute.hackclub.dev/ and did not check the domain 😳 haha... got it :))

**Comment by jessicard** [comment]
@bellesea Hehe no worries at all!

**Comment by sampoder** [comment]
http://contribute.hackclub.com/ 👁️
