### ISSUE TITLE
Link to https://hackclub.com/opensource 

### ISSUE THREAD

**Issue by jessicard** [hackclub/contribute#8]
Add a blurb to the page that links to our open source page, something like

> Transparency is a core value of Hack Club, and code is not the only thing we open source. [Check out our finances, workshops, and more](https://hackclub.com/opensource).

// Edited issue based on @bellesea's idea

**Comment by bellesea** [comment]
> https://hackclub.com/opensource exists, but isn't linked to anywhere. Can we integrate these two somehow? Should we link to it from here?

Maybe we can add a button to the open source page which is smth like "want to contribute?" 

Or instead of the GitHub repositories section, we could replace it with the contribute cards?

**Comment by jessicard** [comment]
@bellesea I like the "want to contribute" button idea!

I was also thinking about replacing that section with cards, but then I was thinking it's kind of cool to see a list of our repositories. 🤔  Maybe we can keep that there and just add the "want to contribute" button, and then link back to the open source page somehow from the contribute page, and then link to one of them in the footer. What do you think?

**Comment by bellesea** [comment]
> @bellesea I like the "want to contribute" button idea!
> 
> I was also thinking about replacing that section with cards, but then I was thinking it's kind of cool to see a list of our repositories. 🤔 Maybe we can keep that there and just add the "want to contribute" button, and then link back to the open source page somehow from the contribute page, and then link to one of them in the footer. What do you think?

ooo hmm, maybe we can add the want contribute button above the list? cuz i'm not sure how many people will actually scroll to the bottom ( quite long hahaha ).

on linking back, we can add smth like "code is not the only thing we open source, check out our finances, workshops, and more..."

**Comment by jessicard** [comment]
@bellesea Oooooh yep yep totally agree. I will edit the issue description with your idea!

**Comment by jessicard** [comment]
Done in https://github.com/hackclub/contribute/commit/6010e42ac8dd143ba49b4e56b2cac797ac73127f
